version: 2.1
orbs:
  python: circleci/python@2
jobs:
  test-python:
    docker:
      - image: cimg/python:3.8-node
    steps:
      - checkout
      - python/install-packages
      - run:
          name: Run tests
          command: echo "no tests aval at this time"
      - store_test_results:
          path: junit.xml
  build-docker-image:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t my-app:${CIRCLE_SHA1} .
  run-docker-tests:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Pull built Docker image
          command: |
            docker image inspect my-app:${CIRCLE_SHA1} || docker build -t my-app:${CIRCLE_SHA1} .
      - run:
          name: Run container and test
          command: |
            docker run --rm my-app:${CIRCLE_SHA1} echo "Container started successfully"
workflows:
  build-and-test:
    jobs:
      - test-python
      - build-docker-image:
          requires:
            - test-python
      - run-docker-tests:
          requires:
            - build-docker-image
